//Types for Data
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
export const SET_CURRENT_PLACE = 'SET_CURRENT_PLACE';
export const SET_CURRENT_BEACON = 'SET_CURRENT_BEACON';
export const SET_BEACON_PLACE_RELATION_BEACON =
  'SET_BEACON_PLACE_RELATION_BEACON';
export const SET_CURRENT_PLACES_DATA = 'SET_CURRENT_PLACES_DATA';
